service: omni-dw-corsair

provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  memorySize: 128 
  timeout: 600
  role : ${ssm:/omni-dw/${self:provider.stage}/lambda/role}
  environment:
    stage: ${self:provider.stage}
  stackTags:
    Application: Omni corsair report
    CreateBy: BizCloudExperts
    Environment: ${self:provider.stage}      

custom:
  prune:
    automatic: true
    number: 3

package:
  individually: true
  excludeDevDependencies: false
  exclude:
    - 'node_modules/**'
    - 'config/**'
    - 'src/**'
    - '*.*'
functions:
    - ${file(config/corsairReport.yml)}
resources:
  Resources:
    MyMetricFilter:
      Type: AWS::Logs::MetricFilter
      Properties:
        LogGroupName: "/aws/lambda/${self:service}-${self:provider.stage}-SendReport"
        FilterPattern: "{$.status = 500}"
        MetricTransformations:
          - MetricValue: "1"
            MetricNamespace: "MyNamespace"
            MetricName: "error-metric-${self:provider.stage}"
    MySNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: "omni-dw-corsair-error-notification-topic-${self:provider.stage}"
        TopicName: "omni-dw-corsair-error-notification-topic-${self:provider.stage}"
    MySNSSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: email
        TopicArn:
          Ref: MySNSTopic
        Endpoint: ${ssm:/omni/support/${self:provider.stage}/alarm/email}
    MyAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmName: corsair-reports-lambda-error-alarm-${self:provider.stage}
        ComparisonOperator: GreaterThanOrEqualToThreshold
        EvaluationPeriods: 1
        MetricName: error-metric-${self:provider.stage}
        Namespace: MyNamespace
        Period: 60
        Statistic: Sum
        Threshold: 1
        ActionsEnabled: true
        AlarmActions:
          - Ref: MySNSTopic

plugins:
  - serverless-offline
  - serverless-prune-plugin

layers:
  commonLibs:
    path: lib
    name: omni-dw-corsair-${self:provider.stage}
    compatibleRuntimes:
      - nodejs18.x
    package:     
      include:
        - node_modules/**
