service: omni-dw-corsair

provider:
  name: aws
  runtime: nodejs14.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  memorySize: 128 
  timeout: 600
  role : ${ssm:/omni-dw/${self:provider.stage}/lambda/role}
  environment:
    stage: ${self:provider.stage}

custom:
  prune:
    automatic: true
    number: 3

package:
  individually: true
  excludeDevDependencies: false
  exclude:
    - 'node_modules/**'
    - 'config/**'
    - 'src/**'
    - '*.*'
functions:
    - ${file(config/corsairReport.yml)}

plugins:
  - serverless-offline
  - serverless-prune-plugin

layers:
  commonLibs:
    path: lib
    compatibleRuntimes:
      - nodejs18.x
    # package:     
    #   include:
    #     - node_modules/**
