SendReport:
  handler: src/CorsairReport/index.handler
  layers:
    - { Ref: CommonLibsLambdaLayer }  
  environment:
    DB_PORT: ${ssm:/omni-dw/corsair/${self:provider.stage}/db/port}
    DB_HOST: ${ssm:/omni-dw/corsair/${self:provider.stage}/db/host}
    DB_PASSWORD: ${ssm:/omni-dw/corsair/${self:provider.stage}/db/password}   
    DB_DATABASE: ${ssm:/omni-dw/corsair/${self:provider.stage}/db/name}
    DB_USER: ${ssm:/omni-dw/corsair/${self:provider.stage}/db/user}
    DEFAULT_AWS: ${self:provider.region}
    SFTP_HOST: ${ssm:/omni-dw/corsair/${self:provider.stage}/sftp/host}
    SFTP_PORT: ${ssm:/omni-dw/corsair/${self:provider.stage}/sftp/port}
    SFTP_USER: ${ssm:/omni-dw/corsair/${self:provider.stage}/sftp/username}
    SFTP_PASSWORD: ${ssm:/omni-dw/corsair/${self:provider.stage}/sftp/password}
    SMTP_HOST: ${ssm:/omni-dw/salesforce/${self:provider.stage}/smtp/host}
    SMTP_PORT: ${ssm:/omni-dw/salesforce/${self:provider.stage}/smtp/port}
    SMTP_USER: ${ssm:/omni-dw/salesforce/${self:provider.stage}/smtp/user}
    SMTP_PASSWORD: ${ssm:/omni-dw/salesforce/${self:provider.stage}/smtp/password}
    SMTP_SENDER: ${ssm:/omni-dw/salesforce/${self:provider.stage}/smtp/sender}
    SMTP_RECEIVER: ${ssm:/omni-dw/corsair/${self:provider.stage}/smtp/receiver}
    SNS_TOPIC_ARN: ${ssm:/omni-reports/${self:provider.stage}/error-notification/sns/arn}
    REGION: ${self:provider.region}

  package:
    individually: true
    include:
        - 'src/CorsairReport/**'
        - 'src/shared/**'
  vpc:
    securityGroupIds:
      - ${ssm:/omni-dw/${self:provider.stage}/lambda/sgId}
    subnetIds:
      - ${ssm:/omni-dw/${self:provider.stage}/lambda/subnetA}
  events:
    - schedule: cron(0 16 * * ? *)
    # - http:
    #     path: /
    #     method: get
    #     cors: true
  alarms:
    - cloudwatchLog:
        logGroupName: "/aws/lambda/${self:service}-${self:provider.stage}-SendReport"
        filterPattern: "ERROR"
        metricName: "ErrorCount"
        threshold: 1
        evaluationPeriods: 1
        comparisonOperator: "GreaterThanOrEqualToThreshold"
        namespace: "AWS/Lambda"
        dimensions:
          - Name: "FunctionName"
            Value: "${self:service}-${self:provider.stage}-SendReport"
        alarmName: "SendReportErrorAlarm"
        treatMissingData: "missing"
        period: 60
        statistic: "Sum"
        actionsEnabled: true
        alarmActions:
          - ${ssm:/omni-reports/${self:provider.stage}/error-notification/sns/arn}
